version: '1'

services:
  monolitico:
    build: ./monolitico
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
  cliente:
    build: ./microservicios/crearcliente
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
  vehiculo:
    build: ./microservicios/nuevoVehiculo
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
  citascliente:
    build: ./microservicios/verCitasCliente
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
  citasrepre:
    build: ./microservicios/verCitasRepre
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
  vertalleres:
    build: ./microservicios/verTalleres
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/test
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - monolitico
      - vehiculo
      - cliente
      - citascliente
      - citasrepre
      - vertalleres
  mongo:
    image: mongo